version: '3.0'
services:
#  db:
#    image: postgres:15.1-alpine
#    container_name: postgres
#    ports:
#      - 5432:5432
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
#    env_file:
#      - .env
    redis:
      image: redis:latest
      hostname: localhost
      ports:
        - 6379:6379
      container_name: redis
